on:
  - push
  - pull_request

jobs:
  compile-sketch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/compile-sketches@v1
        with:
          platforms: |
            - name: 'esp32:esp32:esp32da'
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
          sketch-paths: |
            - ./Controller
          libraries: |
            - name: Bounce2